version: '3'

services:
  vul:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
    image: "spring-cloud-config-server:${VERSION}-RELEASE"
    restart: always
    ports:
       - 8888
